#!/usr/bin/env python3
"""Generate Agent Kali profile.md for each participant.

Gathers data from:
1. LightRAG (ndis workspace) — personal details, NDIS info, diagnosis
2. Local SC folder — reads all PDFs, DOCXs, MDs in the participant's folder
3. Compiles into a structured markdown profile

Usage:
    cd python && .venv/bin/python generate_profiles.py
"""

import os
import sys
import json
import subprocess
import time
from pathlib import Path

# Add parent dir so we can import project modules
sys.path.insert(0, str(Path(__file__).parent))

from sources.folder_source import read_folder_text

SC_ROOT = Path.home() / "Desktop" / "Support-Coordination"
RAG_CLI = Path.home() / ".local" / "bin" / "lightrag"
RAG_API_KEY = "2b1dade2bfee3578c22840f721de3c1a1ad68b0c076ade6420f05f3b0181b587"
RAG_URL = "https://ndis.profexer.cloud"

SKIP_DIRS = {"_Audit-Prep-2026", "Archived", "AGENTS.md", "CLAUDE.md", "MEMORY.md"}


def query_rag(query: str, mode: str = "local") -> str:
    """Query the NDIS RAG workspace via HTTP."""
    import urllib.request
    try:
        data = json.dumps({"query": query, "mode": mode}).encode()
        req = urllib.request.Request(
            f"{RAG_URL}/query",
            data=data,
            headers={
                "Content-Type": "application/json",
                "X-API-Key": RAG_API_KEY,
            },
        )
        with urllib.request.urlopen(req, timeout=25) as resp:
            result = json.loads(resp.read())
            return result.get("response", "")
    except Exception as e:
        print(f"  [RAG] Error: {e}")
        return ""


def get_participant_folders() -> list[tuple[str, Path]]:
    """Return (display_name, folder_path) for each participant."""
    results = []
    for entry in sorted(SC_ROOT.iterdir()):
        if not entry.is_dir():
            continue
        if entry.name in SKIP_DIRS or entry.name.startswith("."):
            continue
        display_name = entry.name.replace("-", " ")
        results.append((display_name, entry))
    return results


def read_participant_folder(folder: Path) -> tuple[str, list[str]]:
    """Read all documents in a participant's folder. Returns (text, files_read)."""
    text, files = read_folder_text(folder, max_chars=80000)
    return text, files


def build_profile_md(name: str, rag_data: str, folder_text: str, files_read: list[str], folder_path: Path) -> str:
    """Build the structured markdown profile."""
    # Parse what we can from the RAG data
    lines = [
        f"# {name} — Agent Kali Profile",
        "",
        f"> Auto-generated on {time.strftime('%d %B %Y at %H:%M')}",
        f"> Source: RAG (ndis.profexer.cloud) + Local folder ({folder_path.name})",
        f"> Files scanned: {len(files_read)}",
        "",
        "---",
        "",
        "## RAG Data (NDIS Workspace)",
        "",
        rag_data.strip() if rag_data.strip() else "_No data returned from RAG for this participant._",
        "",
        "---",
        "",
        "## Local Folder Contents",
        "",
        f"**Folder:** `{folder_path}`",
        f"**Files found:** {len(files_read)}",
        "",
    ]

    if files_read:
        lines.append("### Files Scanned")
        lines.append("")
        for f in files_read:
            lines.append(f"- {f}")
        lines.append("")

    if folder_text.strip():
        lines.append("### Extracted Text")
        lines.append("")
        # Truncate to reasonable size for an MD file
        truncated = folder_text[:60000]
        lines.append(truncated)
        if len(folder_text) > 60000:
            lines.append(f"\n\n_... truncated ({len(folder_text)} total chars)_")
    else:
        lines.append("_No readable text found in folder._")

    lines.extend([
        "",
        "---",
        "",
        f"_Profile generated by Agent Kali for {name}_",
    ])

    return "\n".join(lines)


def generate_profile(name: str, folder: Path) -> str:
    """Generate profile for one participant."""
    print(f"\n{'='*60}")
    print(f"  {name}")
    print(f"{'='*60}")

    # 1. Query RAG
    print(f"  [1/2] Querying RAG for {name}...")
    rag_query = f"{name} date of birth NDIS number address phone email diagnosis plan dates plan management goals providers support needs emergency contact guardian nominee"
    rag_data = query_rag(rag_query, mode="local")
    if rag_data:
        print(f"  [RAG] Got {len(rag_data)} chars")
    else:
        print(f"  [RAG] No data returned")

    # 2. Read local folder
    print(f"  [2/2] Reading local folder: {folder.name}/")
    folder_text, files_read = read_participant_folder(folder)
    print(f"  [Folder] Read {len(files_read)} files, {len(folder_text)} chars")

    # 3. Build profile
    profile = build_profile_md(name, rag_data, folder_text, files_read, folder)

    # 4. Save
    output_dir = folder / "agent-kali"
    output_dir.mkdir(exist_ok=True)
    output_file = output_dir / "profile.md"
    output_file.write_text(profile)
    print(f"  [SAVED] {output_file} ({len(profile)} chars)")

    return str(output_file)


def main():
    participants = get_participant_folders()
    print(f"Found {len(participants)} participants in {SC_ROOT}")
    print()

    saved = []
    for name, folder in participants:
        try:
            path = generate_profile(name, folder)
            saved.append(path)
        except Exception as e:
            print(f"  [ERROR] {name}: {e}")

    print(f"\n{'='*60}")
    print(f"  DONE: {len(saved)}/{len(participants)} profiles generated")
    print(f"{'='*60}")
    for p in saved:
        print(f"  ✓ {p}")


if __name__ == "__main__":
    main()
